---
- name: Build the Cloud Environment
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - ../group_vars/all
    - ../../inventory/aws/group_vars/all
  tasks:
    - name: Create Security Groups
      ec2_group:
        region: "{{ cloud_config.region }}"
        name: "{{ item.name }}"
        vpc_id: "{{ cloud_config.vpc_id }}"
        description: "{{ item.description }}"
        purge_rules: false
        purge_rules_egress: false
        rules: "{{ item.rules }}"
      with_items: "{{ cloud_config.security_groups }}"
      register: cluster_security_groups

    - name: Upload the SSH Key
      ec2_key:
        region: "{{ cloud_config.region }}"
        name: "{{ cloud_config.ssh.keyname }}"
        key_material: "{{ lookup('file', cloud_config.ssh.publickey) }}"
        state: present
        wait: yes

    - name: Build AWS Nodes
      include: build_aws_nodes.yml
      when: item.count > 0
      with_items: "{{ nodes }}"

    - name: Configure Instance Stores
      include: build_aws_nodes.yml
      when: item.count > 0
      with_items: "{{ nodes }}"
