---
- name: Loading list of devices
  uri:
    url: "http://169.254.169.254/2016-06-30/meta-data/block-device-mapping/"
    return_content: yes
  register: devices
 
- name: Load ephemeral device names
  uri:
    url: "http://169.254.169.254/2016-06-30/meta-data/block-device-mapping/{{item}}"
    return_content: yes
  with_items: "{{devices.content.split('\n')}}"
  when: item.startswith('ephemeral')
  register: device_names
 
- name: Create list of device names
  set_fact:
    ephs: "{{ device_names.results | selectattr('content', 'defined') | map(attribute='content') | map('regex_replace', '^sd', '/dev/xvd') | list }}"
 
- name: install the lvm utilities
  yum: name=lvm2 state=present

- name: Create volume group
  lvg: vg=vg.eph pvs="{{ephs | join(',')}}" state=present
 
- name: Create logical volume
  lvol: vg=vg.eph lv=eph size=100%VG state=present opts="-i{{ephs | length}}"
 
- name: Format logical volume
  filesystem: fstype=ext4 dev=/dev/vg.eph/eph
 
- name: Mount logical volume
  mount: name=/mnt src=/dev/vg.eph/eph fstype=ext4 state=mounted
