---

- name: Configuring /etc/login.defs
  template: >
    src=etc-login.defs.j2
    dest=/etc/login.defs
    backup=yes
    owner=root
    group=root
    mode=0644
  tags:
    - system
    - login
    - config
