---
- include: "prepare_node_storage.yml"

- include: "prepare_nodes.yml"

- include: "install_ambari.yml"

- include: "configure_ambari.yml"

- include: "apply_blueprint.yml"

- include: "post_install.yml"
